### ISSUE TITLE
[media] - max-width

### ISSUE THREAD

**Issue by raphaelfabeni** [jgthms/minireset.css#8]
Hey @jgthms ! 
First, congrats for the project. Great idea.

About the media's content: how about adding `iframe` in the _responsive declaration_?

Something like that:

```css
img,
embed,
object,
audio,
video,
iframe {
  height: auto;
  max-width: 100%;
}
```
